name: .NET

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    

jobs:
  build:

    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Stop application
      run: |
       iisreset /stop
    - name: Copy build
      run: cp .\My_Library\bin\Debug\netcoreapp3.1\* C:\Applications\MyLibrary\
    - name: Start application
      run: | 
        iisreset /start

